CREATE TABLE namespace (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	label text UNIQUE NOT NULL
);

CREATE TABLE term (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	label text NOT NULL,
	namespace_id int NOT NULL REFERENCES namespace (id),
	UNIQUE (namespace_id, label)
);

CREATE TABLE language (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text UNIQUE NOT NULL,
	iso_code text UNIQUE NOT NULL
);

CREATE TABLE translation (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	content text NOT NULL,
	term_id int NOT NULL REFERENCES term (id),
	language_id int NOT NULL REFERENCES language (id),
	UNIQUE (term_id, language_id)
);