CREATE TABLE page (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title text UNIQUE NOT NULL,
	content text NOT NULL
);

CREATE TABLE namespace (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	label text UNIQUE NOT NULL
);

CREATE TABLE namespace_page (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	namespace_id int NOT NULL REFERENCES namespace (id),
	page_id int NOT NULL REFERENCES page (id),
	UNIQUE (namespace_id, page_id)
);

CREATE TABLE term (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	label text NOT NULL,
	namespace_id int NOT NULL REFERENCES namespace (id),
	UNIQUE (namespace_id, label)
);

CREATE TABLE language (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text UNIQUE NOT NULL,
	iso_code text UNIQUE NOT NULL
);

CREATE TABLE translation (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	content text NOT NULL,
	term_id int NOT NULL REFERENCES term (id),
	language_id int NOT NULL REFERENCES language (id),
	UNIQUE (term_id, language_id)
);